name: Django checker

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout v3
        uses: actions/checkout@v3
        
      - name: Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }} -pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
    
      - name: pip upgrade
        run: python -m pip install --upgrade pip
      
      - name: requirements installation in django
        run: pip install -r requirements.txt
  
      - name: checking django server if it has no error
        run: |
          python global_farmers/manage.py runserver 0.0.0.0:8000 &
          for i in $(seq 1 10); do
            curl -sSf "http://localhost:8000/" >/dev/null && break
            sleep 1
          done
        
      - name: started successfully
        run: echo started successfully!!
  
  reject:
    needs: build
    if: ${{ needs.build.result == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request Review
        uses: actions/github-script@v3
        with:
          script: |
            const { owner, repo } = context.repo;
            const number = context.payload.pull_request.number;
            const review_id = context.payload.review.id;
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            await octokit.pulls.createReview({
              owner,
              repo,
              pull_number: number,
              body: 'This pull request cannot be merged until all workflow checks pass.',
              event: 'REQUEST_CHANGES',
              review_id
            });
        
        
